### ISSUE TITLE
fix ingress to allow for AWS Load Balancer Controller options

### ISSUE THREAD

**Issue by ns-rkusumoto** [buildbuddy-io/buildbuddy-helm#67]
so I'm fixing the ingress to allow the AWS Load Balancer Controller to create the ingress.

For buildbuddy-http, it looks like:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/backend-protocol-version: HTTP1
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ACMarn
    alb.ingress.kubernetes.io/ip-address-type: ipv4
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    alb.ingress.kubernetes.io/subnets: subnet-A,subnet-B
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: buildbuddy.example.com
  labels:
    app.kubernetes.io/instance: buildbuddy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: buildbuddy
    helm.sh/chart: buildbuddy-0.0.181
  name: buildbuddy-http
  namespace: buildbuddy
spec:
  ingressClassName: alb
  rules:
  - host: buildbuddy.example.com
    http:
      paths:
      - backend:
          service:
            name: buildbuddy
            port:
              name: http
        path: /
        pathType: Prefix
```

for buildbuddy-grpc ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:ACMarn
    alb.ingress.kubernetes.io/ip-address-type: ipv4
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":1985},{"HTTPS":9092}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    alb.ingress.kubernetes.io/subnets: subnet-A,subnet-B
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: buildbuddy-grpc.example.com
  labels:
    app.kubernetes.io/instance: buildbuddy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: buildbuddy
    helm.sh/chart: buildbuddy-0.0.181
  name: buildbuddy-grpc
  namespace: buildbuddy
spec:
  ingressClassName: alb
  rules:
  - host: buildbuddy-grpc.example.com
    http:
      paths:
      - backend:
          service:
            name: buildbuddy
            port:
              name: grpc
        path: /
        pathType: Prefix
      - backend:
          service:
            name: bazel-cache-bazel-remote
            port:
              name: grpc
        path: /cache/
        pathType: Prefix

```
Outside of the alb annotations, need spec.ingressClassName to be used if its defined.
The annotations differ slightly between the 2 ingresses so having that for the values.yaml would be helpful.
FYI using https://github.com/slamdev/helm-charts/tree/master/charts/bazel-remote to do bazel-cache-bazel-remote
